server:
  port: 8090
  servlet:
    context-path: /domofon
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/domofon
    username: postgres
    password: roottppy
    driver-class-name: org.postgresql.Driver

  #jndi-name: jdbc/domofon
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  token:
    secret: roottppy
    expired: 3600000
